name: "Test action"
on:
  pull_request:
jobs:
  do-not-run:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'NOCI') }
    runs-on: ubuntu-latest
    steps:
      - name: get-env
        run: env
      - name: get-event
        run: cat "$GITHUB_EVENT_PATH" | jq -M .
  run:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: echo 'hi'
