name: "Test action"
on:
  push:
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: get-env
        run: env
      - name: get-event
        run: cat "$GITHUB_EVENT_PATH" | jq -M .
      - name: test-echo
        run: |
          echo \
          "{
            \"deployment\": {
              \"revision\": \"{{ github.sha }}\",
              \"changelog\": \" {{ github.event.head_commit.message }}\",
              \"description\": \"Deployed to production: {{ github.event.head_commit }}\",
              \"user\": \"{{ github.event.head_commit.author.username }}\"
            }
          }"
