name: "Test action"
on:
  push:
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: get-env
        run: env
      - name: get-event
        run: cat "$GITHUB_EVENT_PATH" | jq -M .
      - name: full-env-var
        run: echo $GITHUB_SHA
      - name: test-four
        run: echo ${GITHUB_SHA::7}
      - name: export-short
        run: echo "::set-env name=SHORT_SHA::${GITHUB_SHA::7}"
      - name: echo-short
        run: echo $SHORT_SHA
      - name: test-echo
        run: |
          echo \
          "{
            \"deployment\": {
              \"revision\": \"${{ github.sha }}\",
              \"changelog\": \"${{ github.event.head_commit.message }}\",
              \"description\": \"Deployed to production: ${{ github.event.head_commit }}\",
              \"user\": \"${{ github.event.head_commit.author.username }}\"
            }
          }"
